[package]
authors = ["The Knurling-rs developers"]
edition = "2018"
license = "MIT OR Apache-2.0"
name = "defmt-parser"
version = "0.1.0"

[features]
unstable = []

[package.metadata.docs.rs]
rustdoc-args = [ "--cfg docsrs" ]